name: Run API Tests (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Escolha o ambiente"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v5

      - name: 🟢 Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: 📦 Instalar Bruno CLI
        run: npm install -g @usebruno/cli

      - name: 🔧 Definir URL por ambiente
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "BASE_URL=https://petstore.swagger.io/v2" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            echo "BASE_URL=https://api.prod.com" >> $GITHUB_ENV
          fi

      - name: 🧪 Rodar testes
        run: |
          cd tests/smoke
          bru run user login \
            --env-var baseurl=$BASE_URL
